export const EVENTS = [
  {
    image: "/images/event1.png",
    title: "Open Source Summit",
    slug: "open-source-summit",
    location: "San Francisco, CA",
    date: "May 14, 2026",
    time: "10:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "Frontend Future Conf",
    slug: "frontend-future-conf",
    location: "Berlin, Germany",
    date: "June 3, 2026",
    time: "9:30 AM",
  },
  {
    image: "/images/event3.png",
    title: "AI Leaders Forum",
    slug: "ai-leaders-forum",
    location: "New York, NY",
    date: "July 9, 2026",
    time: "1:00 PM",
  },
  {
    image: "/images/event4.png",
    title: "Build Week Live",
    slug: "build-week-live",
    location: "Austin, TX",
    date: "August 21, 2026",
    time: "11:00 AM",
  },
  {
    image: "/images/event5.png",
    title: "Cloud Dev Summit",
    slug: "cloud-dev-summit",
    location: "Seattle, WA",
    date: "September 17, 2026",
    time: "2:30 PM",
  },
  {
    image: "/images/event6.png",
    title: "Product Engineering Meetup",
    slug: "product-engineering-meetup",
    location: "London, UK",
    date: "October 6, 2026",
    time: "6:00 PM",
  },
  {
    image: "/images/event-full.png",
    title: "Platform Launch Keynote",
    slug: "platform-launch-keynote",
    location: "Remote + San Jose, CA",
    date: "November 12, 2026",
    time: "5:00 PM",
  },
];
